[package]
name        = "stardome"
version     = "0.1.0"
authors     = ["AlexApps99 <alex.apps99@gmail.com>"]
edition     = "2018"

publish     = false
description = "Planet visualization"
repository  = "https://github.com/AlexApps99/stardome"

[dependencies.gl]
version     = "0.14"

[dependencies.glam]
version     = "0.9"

[dependencies.imgui]
version     = "0.4"
optional    = true

[dependencies.imgui-opengl-renderer]
version     = "0.8"
optional    = true

[dependencies.imgui-sdl2]
version     = "0.11"
optional    = true

[dependencies.png]
version     = "0.4.1"
default-features = false

[dependencies.sdl2]
version     = "0.34.3"

[features]
default     = []
gui         = ["imgui", "imgui-opengl-renderer", "imgui-sdl2"]
